id: I530A19E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:32:26+00:00'
last_modified: '2022-06-08T12:03:50.522417+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30408
  title: ཇོ་ནང་བའི་གདན་རབས་མདོར་བསྡུས་དྲང་སྲོང་རྒན་པོའི་ཞལ་ལུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3DE6:
      image_group_id: I1GS105508
      title: Volume 1 of jo nang ba'i gdan rabs mdor bsdus drang srong rgan po'i zhal
        lung
      total_pages: 254
      order: 1
      base_file: 3DE6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
