id: P007018
initial_creation_type: ocr
source_metadata:
  id: bdr:W30408
  title: ཇོ་ནང་བའི་གདན་རབས་མདོར་བསྡུས་དྲང་སྲོང་རྒན་པོའི་ཞལ་ལུང
  author: ''
  volumes:
    fca3d50b19eb48029d1e9301f4d6abf4:
      image_group_id: I1GS105508
      title: ''
      volume_number: 1
      total_pages: 254
ebook_metadata:
  title: ཇོ་ནང་བའི་གདན་རབས་མདོར་བསྡུས་དྲང་སྲོང་རྒན་པོའི་ཞལ་ལུང
  author: ''
  sku: P007018
  cover: cover.jpg
  layers:
  - pagination
