id: P007018
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:32.138309
source_metadata:
  id: bdr:W30408
  title: ཇོ་ནང་བའི་གདན་རབས་མདོར་བསྡུས་དྲང་སྲོང་རྒན་པོའི་ཞལ་ལུང
  author: ''
  volumes:
    4fe773404209461d88743a4b7aab86f7:
      image_group_id: I1GS105508
      title: Volume 1 of jo nang ba'i gdan rabs mdor bsdus drang srong rgan po'i zhal
        lung
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
